[features]
seeds = false
[programs.devnet]
blastfm = "XNFCVpn6ujGoEEsDJxQWJ36k7HnUQVPzrWc3YBosq9u"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/solom/.config/solana/id.json"

[scripts]
test = "node tests/blastfm.js" 
